version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/WorkerService"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "nuget"
    directory: "/WorkerUpdater"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
